name: 'Build Feature Branches'

on: workflow_call

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Creates file "$/files.json", among others
      - name: build
        run: |
          echo 'features/service build pipe'