name: 'Build Feature Branches'

on: workflow_call
# on: 
#   workflow_call:
#     inputs:
#       workflows-ref:
#         description: "ref of the centralized workflows repo that was specified in 'jobs.<name>.uses'"
#         required: true
#         type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Creates file "$/files.json", among others
      - name: build
        run: |
          echo 'features/service build pipe'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Creates file "$/files.json", among others
      - name: deploy
        run: |
          echo 'features/service deploy pipe'