name: 'Build Main Branch'

on: 
  workflow_call:
    inputs:
      workflows-ref:
        description: "ref of the centralized workflows repo that was specified in 'jobs.<name>.uses'"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ inputs.workflows-ref }}
      #     path: workflows
      #     repository: zfael/gh-actions-workflow-called
      #     token: ${{ secrets.GH_ACCESSTOKEN }}

      # - name: Build
      #   id: build-action
      #   uses: ./workflows/.github/actions/build-action
      #   with:
      #     name: "main"
      #     project-type: "service"

      - name: build
        run: |
          echo 'main/service build pipe'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: deploy
        run: |
          echo 'main/service deploy'