name: 'Build Main Branch'

on: workflow_call

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          echo 'main/service build pipe'